use_frameworks!
source 'https://github.com/CocoaPods/specs.git'
source 'git@github.com:yangyangDeveloper/ZYYSpecs.git'

platform :ios, '10.0'

target 'OCPodThree_Example' do
  pod 'OCPodThree', :path => '../'
  
  #pod 'OCPodThree',:podspec => '../OCPodThree.podspec'
  
  target 'OCPodThree_Tests' do
    inherit! :search_paths

    
  end
end
